### ISSUE TITLE
Maftools doesn't compile with sonlib out of the box

### ISSUE THREAD

**Issue by cganote** [benedictpaten/sonLib#26]
Hi,

I see an error when I try to compile MafTools:
gcc -std=c99 -c src/comparatorRandom.c -o src/comparatorRandom.o.tmp -O3 -Wall -Werror --pedantic -funroll-loops -DNDEBUG -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -I ../../sonLib/lib -I ../inc -I ../external 
cc1: warnings being treated as errors
In file included from ../../sonLib/lib/sonLib.h:36,
                 from src/comparatorRandom.h:30,
                 from src/comparatorRandom.c:28:
../../sonLib/lib/sonLibEulerTour.h:16: error: function declaration isn’t a prototype

I'm not sure why strict flags are set. I added 'void' to the call in EulerTour and it compiles now.
-Carrie

**Comment by adderan** [comment]
Thanks! Fixed now.
